# Default values. Use --build-arg on build to change
ARG pyversion=3.12

# Base pyton image
FROM python:$pyversion

# Update pip
RUN pip install --upgrade pip

# WORKDIR /tmp
# COPY ./wheels/ ./wheels/

# Copy dependency manifest from Kratos GiD
COPY kratos.gid/kratos.xml /tmp/kratos.xml
COPY dockers/generate_requirements_from_xml.py /tmp/generate_requirements_from_xml.py

# Install Kratos packages listed in kratos.xml
RUN python3 /tmp/generate_requirements_from_xml.py --xml /tmp/kratos.xml --out /tmp/requirements.txt \
    && python3 -m pip install --no-cache-dir -r /tmp/requirements.txt
# RUN python3 -m pip install ./wheels/*.whl

# Prepare run folder
WORKDIR "/model"
RUN chmod 777 /model

# Kratos will start on docker run
CMD [ "python3", "MainKratos.py" ]

# docker build -t kratos-run -f dockers/dockerfile .
# docker run -rm -it  --entrypoint bash kratos-run
