FROM python:3.9

RUN pip install KratosMultiphysics-all==9.2 numpy
WORKDIR /model
RUN chmod 777 /model
ENTRYPOINT [ "python3", "MainKratos.py" ]

# docker build -t kratos-run:latest -t kratos-run:9.2 .
# docker tag kratos-run:latest fjgarate/kratos-run:latest
# docker tag kratos-run:9.2 fjgarate/kratos-run:9.2
# docker push fjgarate/kratos-run:latest
# docker push fjgarate/kratos-run:9.2