# Default values. Use --build-arg on build to change
ARG pyversion=3.11

# Base pyton image
FROM python:$pyversion
# FROM python:3.10.10-alpine3.17

# Update pip
RUN pip install --upgrade pip

ARG krversion=9.4.2

# WORKDIR /tmp
# COPY ./wheels/ ./wheels/

# Install Kratos and dependencies
RUN python3 -m pip install KratosMultiphysics-all==$krversion numpy
# RUN python3 -m pip install ./wheels/*.whl

# Prepare run folder
WORKDIR "/model"
RUN chmod 777 /model

# Kratos will start on docker run
ENTRYPOINT [ "python3", "MainKratos.py" ]

# docker build -t kratos-run .
# docker run -rm -it  --entrypoint bash kratos-run
