import KratosMultiphysics
import KratosMultiphysics.LinearSolversApplication
import KratosMultiphysics.SolidMechanicsApplication
import KratosMultiphysics.ConstitutiveModelsApplication
import KratosMultiphysics.SolidMechanicsApplication.MainSolid as MainSolid

MainSolid.Solution(KratosMultiphysics.Model()).Run()

