import KratosMultiphysics
import KratosMultiphysics.ExternalSolversApplication
import KratosMultiphysics.PfemApplication
import KratosMultiphysics.SolidMechanicsApplication
import KratosMultiphysics.ConstitutiveModelsApplication
import KratosMultiphysics.ContactMechanicsApplication
import KratosMultiphysics.PfemSolidMechanicsApplication
import MainSolid

MainSolid.Solution().Run()

