import KratosMultiphysics
import KratosMultiphysics.ExternalSolversApplication
import KratosMultiphysics.SolidMechanicsApplication
import KratosMultiphysics.ConstitutiveModelsApplication
import KratosMultiphysics.DelaunayMeshingApplication
import KratosMultiphysics.PfemApplication
import MainPfem

MainPfem.PfemSolution().Run()
