import KratosMultiphysics
import KratosMultiphysics.ExternalSolversApplication
import KratosMultiphysics.DelaunayMeshingApplication
import KratosMultiphysics.PfemApplication
import KratosMultiphysics.SolidMechanicsApplication

import MainSolid

MainSolid.Solution().Run()
