name: Tester

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: fjgarate/kratos-tester:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Copy problemtype to gid and copy exec
      - name: Move kratos where it should be
        run: |
          mv ./kratos.gid /gid/problemtypes/
          mkdir /gid/problemtypes/kratos.gid/exec/Kratos
          mv /tmp/KratosRelease/* /gid/problemtypes/kratos.gid/exec/Kratos

      # start the tester thing
      - name: Tester
        run: |
          cd /app
          npm start
