name: Tester

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GITHUB_ACTION: true

    container:
      image: fjgarate/kratos-tester:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install bins
        run: |
          pip install --upgrade --force-reinstall --no-cache-dir KratosMultiphysics-all==9.2

      # Copy problemtype to gid and copy exec
      - name: Move kratos where it should be
        run: |
          rm -rf /gid/problemtypes/
          mkdir /gid/problemtypes
          mv $GITHUB_WORKSPACE/kratos.gid /gid/problemtypes/

      # start the tester thing
      - name: Tester
        run: |
          cd /app
          npm start
